
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 19.Nis.2011, 03:36:26
 */

/**
 *
 * @author Salih
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public int[] salih;
    public int chips;
    public int pile;
    public int totalChips=30;
    public int i;
    public int k=0;
       public boolean buldum=false;
       Random generator = new Random();
       public boolean cpuwin=false;
       public boolean youwin=false;


    public NewJFrame() {
        initComponents();
        
        salih= new int[6];

        salih[0]=5;
        salih[1]=5;
        salih[2]=5;
        salih[3]=5;
        salih[4]=5;
        salih[5]=5;


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOK = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        pileBox = new javax.swing.JComboBox();
        chipBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newgame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTextField1.setText("5");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTextField2.setText("5");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTextField3.setText("5");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTextField4.setText("5");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setText("5");

        pileBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        chipBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel1.setText("Pile");

        jLabel2.setText("Chip");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.setText("5");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel3.setText("You have no chance to win.Cpu will always win.© 2011 Salih ERİKCİ");

        newgame.setText("New Game");
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pileBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chipBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(newgame)
                        .addComponent(jLabel3)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pileBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chipBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(newgame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        System.out.println(Integer.toString(45^32));

        //KONTROL OYUNCU İÇİN

        //KONTROL OYUNCU İÇİN

        //Oyuncunun girdiği veriyi alıyoruz
        
        
        pile=Integer.parseInt(pileBox.getSelectedItem().toString())-1;
        chips=Integer.parseInt(chipBox.getSelectedItem().toString());
        //oyuncunun girdiği veriyi  aldık

        //Yeteri kadar chip var mı ??
        if(salih[pile]<chips || salih[pile]==0){
         JOptionPane.showMessageDialog(null, "illeagal move try again!");
        }
        //Kontrol ettik

        //Pile ları değiştiriyoruz
        else
        {
        salih[pile]=salih[pile]-chips;
        btnOK.setEnabled(false);
        totalChips=totalChips-chips;
        }

        if(pile==0){jTextField1.setText(Integer.toString(salih[pile]));}
        if(pile==1){jTextField2.setText(Integer.toString(salih[pile]));}
        if(pile==2){jTextField3.setText(Integer.toString(salih[pile]));}
        if(pile==3){jTextField4.setText(Integer.toString(salih[pile]));}
        if(pile==4){jTextField5.setText(Integer.toString(salih[pile]));}
                if(pile==5){jTextField6.setText(Integer.toString(salih[pile]));}



 k=1;
                            if(totalChips==0 ){
                        JOptionPane.showMessageDialog(null, "You Win!");

        k++;
        youwin=true;
        btnOK.setEnabled(false);
        }
        //Pile ları değiştirdik

        // BİLGİSAYAR DA SIRA????????????????????????????????

        //OYUN BİTMİŞ Mİ KONTROL EDİYORUZ
       
        //KONTROL ETTİK


         if(btnOK.isEnabled()==false&&youwin==false)
        {
            i=0;
        while(i<6 && buldum==false){
            System.out.println("195.satır");
            int xor=salih[(i+1)%6]^salih[(i+2)%6]^salih[(i+3)%6]^salih[(i+4)%6]^salih[(i+5)%6];System.out.println(Integer.toString(xor));
            System.out.println("xor = "+Integer.toString(xor));
            if(xor<salih[i]){System.out.println("197.satır");
            pile=i;System.out.println("198.satır");
            chips=salih[i]-xor;System.out.println("199.satır");
            
            buldum=true;
            }
            i++;System.out.println("200.satır");
        }
        while(buldum==false){
            System.out.println("205.satır");
        int rastgelepile = generator.nextInt(6);
        
        if(salih[rastgelepile]>0){
        int rastgelechip=generator.nextInt(salih[rastgelepile]);
        rastgelechip=rastgelechip+1;
        buldum=true;
        pile=rastgelepile;
        chips=rastgelechip;
        }
        }
            salih[pile]=salih[pile]-chips;
            buldum=false;
        if(pile==0){jTextField1.setText(Integer.toString(salih[pile]));}
        if(pile==1){jTextField2.setText(Integer.toString(salih[pile]));}
        if(pile==2){jTextField3.setText(Integer.toString(salih[pile]));}
        if(pile==3){jTextField4.setText(Integer.toString(salih[pile]));}
        if(pile==4){jTextField5.setText(Integer.toString(salih[pile]));}
                    if(pile==5){jTextField6.setText(Integer.toString(salih[pile]));}

            btnOK.setEnabled(true);
            totalChips=totalChips-chips;
                    if(totalChips==0 ){
                        JOptionPane.showMessageDialog(null, "CPU Wins!");
        System.out.println("CPU Wins");
        k++;
        cpuwin=true;
        btnOK.setEnabled(false);
        }
        }
        

    }//GEN-LAST:event_btnOKActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // TODO add your handling code here:
        btnOK.setEnabled(true);
                salih[0]=5;
        salih[1]=5;
        salih[2]=5;
        salih[3]=5;
        salih[4]=5;
        salih[5]=5;
        youwin=false;
        cpuwin=false;
        buldum=false;
        totalChips=30;
        jTextField1.setText("5");
                jTextField2.setText("5");

                        jTextField3.setText("5");

                                jTextField4.setText("5");

                                        jTextField5.setText("5");

                                                jTextField6.setText("5");

    }//GEN-LAST:event_newgameActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnOK;
    private javax.swing.JComboBox chipBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton newgame;
    private javax.swing.JComboBox pileBox;
    // End of variables declaration//GEN-END:variables

}
